# Generated by Django 3.1.7 on 2021-07-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_manga', models.BooleanField(default=True, verbose_name='Manga?')),
                ('is_anime', models.BooleanField(default=False, verbose_name='Anime?')),
                ('created_by', models.CharField(max_length=500, verbose_name='Creator')),
                ('animation_studio', models.CharField(max_length=500, verbose_name='Animation Studio')),
                ('status', models.BooleanField(default=False, verbose_name='Completely Published?')),
                ('episodes', models.IntegerField(default=13, verbose_name='Total Episodes or Volumes')),
                ('personal_status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('F', 'Finished'), ('UD', 'Up to Date')], default='P', max_length=2, verbose_name='Personal Status')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
